### ISSUE TITLE
Right-click menu is sometimes blocked

### ISSUE THREAD

**Issue by hsywhu** [murongqimiao/DAG-diagram#13]
The right-click menu will be partially hidden if the node is at the bottom or the right side of the canvas since the menu is always expanded at the bottom right of the click place.
![image](https://user-images.githubusercontent.com/15964179/68504075-1f40cd80-0219-11ea-8af5-0c80aef03ca5.png)
![image](https://user-images.githubusercontent.com/15964179/68504188-4d261200-0219-11ea-95a6-8e367f1efb2d.png)

Is it possible to change the place to show the menu in these situations? For example, make the menu shows on top of the click place if it's near the bottom of the canvas.

**Comment by murongqimiao** [comment]
halo ! sorry so late to reply~ 
i suppose that the area beside the SVG container need show instead of cover by node right menu.
SVG container is a window to show DAG graph and other area has their own things to do , 
if you need to see the whole menu ~
press left mouse and move the graph~

obvious, if u had to do it  ( eg:  pushing by your PM ? LOL)  u can change the z-index and  make element css into overflow: visible , and so on ~

if u can`t do it yourself , can join our QQ group find some help 793841737

**Comment by hsywhu** [comment]
Thanks!
